### PR TITLE
Add testing farm docs skeleton

### PR DESCRIPTION
**Pull request by thrix**
Signed-off-by: Miroslav Vadkerti <mvadkert@redhat.com>

### CODE REVIEW

**Comment by psss** [comment]
@thrix, what's the status here?

**Comment by psss** [comment]
@thrix, it seems you've included vim's temporary file as well.

**Comment by psss** [comment]
I've reviewed the doc and fixed a couple of minor issues. I think we are ready to squash and move the PR to the packit repo.

**Comment by thrix** [comment]
@psss ack, thanks very much! Squashing and proposing to upstream

**Comment by thrix** [comment]
Closing

**Pull request closed without merging**
